/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f1_gpio.h>
int a = 0;
void delay(){
	for(uint32_t i = 0; i < 333294; i++);
}

int main(void)
{
	GPIO_Handle_t GPIO13;
	GPIO13.pGPIOx = GPIOC;
	GPIO13.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_PP_10MHz;
	GPIO13.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO13.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_Init(&GPIO13);

	GPIO_Handle_t btn;
	btn.pGPIOx = GPIOB;
	btn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT_PULL;
	btn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	btn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
	btn.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_MODE_IT_FT;
	GPIO_Init(&btn);

//	GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_13, GPIO_PIN_SET);
//	GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, 3);
//	GPIO_IRQInteruptConfig(IRQ_NO_EXTI15_10, ENABLE);
	while (1)
	{
		GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
		delay();
	}
	
	return 0;
}

//void EXTI15_10_IRQHandler()
//{
//	delay();
//	GPIO_IRQHandler(GPIO_PIN_NO_12);
//	GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
//	a++;
//}
